#!/usr/bin/env zsh

set -e
target="$1"
shift
ssh_arguments=("$@")
routes=(
  "lan-$target.guzek.uk" "LAN"
  "vpn-$target.guzek.uk" "VPN"
  "ssh-$target.guzek.uk" "Cloudflare tunnel"
)
PING_TIMEOUT_SECONDS=0.1

test_connection() {
  local address="$1"
  local label="$2"
  log-status info "Attempting connection to $target via $label"
  ping -c 1 -W "$PING_TIMEOUT_SECONDS" "$address" >/dev/null 2>&1
}

succeed() {
  local address="$1"
  local label="$2"
  log-status complete "Successful connection to $target via $label"
  exec ssh -t "$address" $ssh_arguments
}


for host label in ${(kv)routes}; do
  if test_connection "$host" "$label"; then
    succeed "$host" "$label"
    exit 0
  fi
done

log-status failed "No available route to $target"
exit 1
