#!/usr/bin/env zsh

set -e
PING_TIMEOUT_SECONDS=0.1
target="$1"
shift
target_hostname="${target#*@}"
ssh_arguments=("$@")
routes=(
  "$target_hostname.lan.guzek.uk" "LAN"
  "$target_hostname.vpn.guzek.uk" "VPN"
  "ssh-$target_hostname.guzek.uk" "Cloudflare tunnel"
)
if [ "$target" = "$target_hostname" ]; then
  target_user=""
else
  target_user="${target%@*}@"
fi

test_connection() {
  local address="$1"
  local label="$2"
  log-status info "Attempting connection to $target via $label"
  ping -c 1 -W "$PING_TIMEOUT_SECONDS" "$address" >/dev/null 2>&1
}

succeed() {
  local address="$1"
  local label="$2"
  log-status complete "Successful connection to $target via $label"
  exec ssh -t "$target_user$address" $ssh_arguments
}


for host label in ${(kv)routes}; do
  if test_connection "$host" "$label"; then
    succeed "$host" "$label"
    exit 0
  fi
done

log-status failed "No available route to $target"
exit 1
