#!/usr/bin/env zsh

set -e

TARGET="$1"
PROGRAM_NAME="${0:t}"

declare -A MAC_ADDRESSES=(
  hp 3c:52:82:76:8d:92
  pi b8:27:eb:20:76:89
  rig 18:c0:4d:39:46:c6
)

declare -a TARGETS=(${(ok)MAC_ADDRESSES})

declare -A WOL_EXTERNAL_PORTS=(
  pi 1904
  hp 1907
  rig 1909
)

print_hint() {
  echo "Try '$PROGRAM_NAME --help' for more information." >&2
}

print_usage() {
  echo "Usage: $PROGRAM_NAME [OPTION] TARGET"
  echo "where TARGET := { ${(j: | :)TARGETS} }"
  echo
  echo 'Options:'
  echo '  --help, -h'
  echo '        display help message and exit'
  echo '  --list, -l'
  echo '        display a space-separated list of available targets and exit'
}

if [ -z "$TARGET" ]; then
  log-status failed "$PROGRAM_NAME: missing target" >&2
  print_hint
  exit 1
fi

if [ "$TARGET" = '-h' ] || [ "$TARGET" = '--help' ]; then
  print_usage
  exit 0
fi

if [ "$TARGET" = '-l' ] || [ "$TARGET" = '--list' ]; then
  echo "${(j: :)TARGETS}"
  exit 0
fi

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

if command_exists wol; then
  WAKE_COMMAND='wol'
elif command_exists wakeonlan; then
  WAKE_COMMAND='wakeonlan'
else
  log-status failed "Neither wakeonlan nor wol are available on the system. Install a supported tool and retry."
  exit 2
fi

if [[ -n "${MAC_ADDRESSES[$TARGET]}" ]]; then
  mac_address="${MAC_ADDRESSES[$TARGET]}"
  wol_external_port="${WOL_EXTERNAL_PORTS[$TARGET]}"

  if [[ -z "$wol_external_port" ]]; then
    log-status failed "No WoL port configured for target: $TARGET"
    exit 2
  fi

  dig_output="$(dig +short "$TARGET.guzek.uk")"
  dig_responses=("${(f)dig_output}")
  log-status info "Resolved address: $TARGET.guzek.uk -> ${${(j: -> :)dig_responses}//. / }"
  NETWORK_IP_ADDRESS="${dig_responses[-1]}"
  wake_output=$("$WAKE_COMMAND" -i "$NETWORK_IP_ADDRESS" -p "$wol_external_port" "$mac_address")
  log-status info "$wake_output"
  log-status complete "Successfully sent wake packet to $TARGET via ${dig_responses[1]}"
  exit 0
fi

log-status failed "$PROGRAM_NAME: '$TARGET': invalid target"
print_hint
exit 1
