#!/bin/bash

WEBHOOK_PAYLOAD_URL='https://ci.guzek.uk'

REPO_NAME="$1"
REPO_OWNER="${2:-kguzek}"

if [[ -z "$REPO_NAME" || ! "$REPO_NAME" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
	log-status failed "Invalid repository name '$REPO_NAME'"
  exit 1
fi

APP_DIR="/data/apps/$REPO_NAME"
if [ -d $APP_DIR ]; then
	log-status unchanged "Skipping clone (directory exists)"
else
  if ! git clone git@github.com:$REPO_OWNER/$REPO_NAME $APP_DIR; then
	  log-status failed "Failed to clone repository"
    exit 2
	fi
  log-status changed "Cloned repository successfully"
fi

if ! git config --global --get-all safe.directory | grep $APP_DIR >/dev/null; then
	git config --global --add safe.directory $APP_DIR
	log-status changed "Added $APP_DIR to the list of safe git directories"
fi
# sudo chown -R konrad:gad $APP_DIR
chmod -R g+rw $APP_DIR

DEPLOY_COMMAND=$(log-status input 'Post-push deploy command: ')
SETTINGS_FILE='/data/apps/Git-Auto-Deploy/config.json'
SECRET_TOKEN=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 20 | head -n 1)
NEW_REPO_ENTRY="{
  \"url\": \"https://github.com/$REPO_OWNER/$REPO_NAME.git\",
  \"branch\": \"main\",
  \"path\": \"$APP_DIR\",
  \"deploy\": $(jq -n --arg var "$DEPLOY_COMMAND" '$var'),
  \"secret-token\": \"$SECRET_TOKEN\"
}"
TEMP_SETTINGS_FILE="$SETTINGS_FILE.new"
SETTINGS_WITHOUT_REPOSITORIES=$(sed -n '1,/"repositories":/{\/\"repositories\":/!p}' "$SETTINGS_FILE")
PREVIOUS_REPOSITORIES=$(sed -n '/"repositories":/,$p' "$SETTINGS_FILE")
if [ -z "$PREVIOUS_REPOSITORIES" ]; then
	log-status failed "Could not parse the repositories field."
  exit 3
fi
PREVIOUS_REPOSITORIES="{$PREVIOUS_REPOSITORIES"

if ! echo "$PREVIOUS_REPOSITORIES" | jq -e ".repositories | map(.path != \"$APP_DIR\") | all" >/dev/null; then
	echo "$PREVIOUS_REPOSITORIES"
	log-status failed "This repository has already been added to the CI/CD pipeline."
  exit 4
fi

UPDATED_REPOSITORIES=$(echo "$PREVIOUS_REPOSITORIES" | jq ".repositories += [$NEW_REPO_ENTRY]" | sed '1d')
if [ $? -ne 0 ]; then
	echo "$PREVIOUS_REPOSITORIES"
	log-status failed "Failed to parse settings file."
  exit 5
fi
echo "$SETTINGS_WITHOUT_REPOSITORIES" > "$TEMP_SETTINGS_FILE"
echo >> "$TEMP_SETTINGS_FILE"
echo "$UPDATED_REPOSITORIES" >> "$TEMP_SETTINGS_FILE"

mv "$TEMP_SETTINGS_FILE" "$SETTINGS_FILE"
log-status complete "Successfully created repository CI/CD configuration"
log-status info "Payload URL  (for GitHub webhook): $WEBHOOK_PAYLOAD_URL"
log-status info "Secret token (for GitHub webhook): $SECRET_TOKEN"
log-status info "Restart the Git Auto Deploy service for configuration to take effect:"
echo "sudo systemctl restart gitautodeploy"
